#!/bin/bash
set -euo pipefail
#
# This script provides helper functions for creating JSON request bodies for the Routes API v2.
# It is meant to be sourced by other scripts.
#
# DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY A SCRIPT.
#
# Discovery Doc Revision: 20260706
#
# For more information, see the official documentation:
# https://developers.google.com/maps/documentation/routes/

# --- Helper functions ---

# Create a JSON object for a LatLng
#
# @param string latitude The latitude in degrees.
# @param string longitude The longitude in degrees.
# @return string The JSON object.
create_lat_lng_json() {
  local latitude="$1"
  local longitude="$2"
  jq -n \
    --argjson latitude "${latitude}" \
    --argjson longitude "${longitude}" \
    '{
      "latitude": $latitude,
      "longitude": $longitude
    }'
}

# Create a JSON object for a Location
#
# @param string lat_lng_json The JSON object for LatLng.
# @param string heading Optional. The compass heading associated with the direction of the flow of traffic.
# @return string The JSON object.
create_location_json() {
  local lat_lng_json="$1"
  local heading="${2:-""}"

  local json_output="{}"
  json_output=$(echo "${json_output}" | jq --argjson latLng "${lat_lng_json}" '.latLng = $latLng')

  if [[ -n "${heading}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson heading "${heading}" '.heading = $heading')
  fi

  echo "${json_output}"
}

# Create a JSON object for a Waypoint
#
# @param string location_json Optional. The JSON object for Location.
# @param string place_id Optional. The POI Place ID associated with the waypoint.
# @param string address Optional. Human readable address or a plus code.
# @param string via Optional. Marks this waypoint as a milestone rather a stopping point.
# @param string vehicle_stopover Optional. Indicates that the waypoint is meant for vehicles to stop at.
# @param string side_of_road Optional. Indicates that the location of this waypoint is meant to have a preference for the vehicle to stop at a particular side of road.
# @return string The JSON object.
create_waypoint_json() {
  local location_json="${1:-""}"
  local place_id="${2:-""}"
  local address="${3:-""}"
  local via="${4:-""}"
  local vehicle_stopover="${5:-""}"
  local side_of_road="${6:-""}"

  local json_output="{}"
  if [[ -n "${location_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson location "${location_json}" '.location = $location')
  fi
  if [[ -n "${place_id}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg placeId "${place_id}" '.placeId = $placeId')
  fi
  if [[ -n "${address}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg address "${address}" '.address = $address')
  fi
  if [[ -n "${via}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson via "${via}" '.via = $via')
  fi
  if [[ -n "${vehicle_stopover}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson vehicleStopover "${vehicle_stopover}" '.vehicleStopover = $vehicleStopover')
  fi
  if [[ -n "${side_of_road}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson sideOfRoad "${side_of_road}" '.sideOfRoad = $sideOfRoad')
  fi

  echo "${json_output}"
}

# Create a JSON object for a RouteModifiers
#
# @param string avoid_tolls Optional. When set to true, avoids toll roads.
# @param string avoid_highways Optional. When set to true, avoids highways.
# @param string avoid_ferries Optional. When set to true, avoids ferries.
# @param string avoid_indoor Optional. When set to true, avoids navigating indoors.
# @param string vehicle_info_json Optional. The JSON object for VehicleInfo.
# @param string toll_passes_json Optional. A JSON array of toll passes.
# @param string avoid_tunnels Optional. When set to true, avoids tunnels.
# @return string The JSON object.
create_route_modifiers_json() {
  local avoid_tolls="${1:-""}"
  local avoid_highways="${2:-""}"
  local avoid_ferries="${3:-""}"
  local avoid_indoor="${4:-""}"
  local vehicle_info_json="${5:-""}"
  local toll_passes_json="${6:-""}"
  local avoid_tunnels="${7:-""}"

  local json_output="{}"
  if [[ -n "${avoid_tolls}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson avoidTolls "${avoid_tolls}" '.avoidTolls = $avoidTolls')
  fi
  if [[ -n "${avoid_highways}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson avoidHighways "${avoid_highways}" '.avoidHighways = $avoidHighways')
  fi
  if [[ -n "${avoid_ferries}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson avoidFerries "${avoid_ferries}" '.avoidFerries = $avoidFerries')
  fi
  if [[ -n "${avoid_indoor}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson avoidIndoor "${avoid_indoor}" '.avoidIndoor = $avoidIndoor')
  fi
  if [[ -n "${vehicle_info_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson vehicleInfo "${vehicle_info_json}" '.vehicleInfo = $vehicleInfo')
  fi
  if [[ -n "${toll_passes_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson tollPasses "${toll_passes_json}" '.tollPasses = $tollPasses')
  fi
  if [[ -n "${avoid_tunnels}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson avoidTunnels "${avoid_tunnels}" '.avoidTunnels = $avoidTunnels')
  fi

  echo "${json_output}"
}

# Create a JSON object for a VehicleInfo
#
# @param string emission_type Optional. Describes the vehicle's emission type.
# @return string The JSON object.
create_vehicle_info_json() {
  local emission_type="${1:-""}"

  local json_output="{}"
  if [[ -n "${emission_type}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg emissionType "${emission_type}" '.emissionType = $emissionType')
  fi

  echo "${json_output}"
}

# Create a JSON object for a TransitPreferences
#
# @param string allowed_travel_modes_json Optional. A JSON array of allowed travel modes.
# @param string routing_preference Optional. A routing preference that, when specified, influences the TRANSIT route returned.
# @return string The JSON object.
create_transit_preferences_json() {
  local allowed_travel_modes_json="${1:-""}"
  local routing_preference="${2:-""}"

  local json_output="{}"
  if [[ -n "${allowed_travel_modes_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson allowedTravelModes "${allowed_travel_modes_json}" '.allowedTravelModes = $allowedTravelModes')
  fi
  if [[ -n "${routing_preference}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg routingPreference "${routing_preference}" '.routingPreference = $routingPreference')
  fi

  echo "${json_output}"
}

# Create a JSON object for a ComputeRoutesRequest
#
# @param string origin_json Required. The JSON object for the origin Waypoint.
# @param string destination_json Required. The JSON object for the destination Waypoint.
# @param string intermediates_json Optional. A JSON array of intermediate Waypoint objects.
# @param string travel_mode Optional. The mode of transportation.
# @param string routing_preference Optional. Specifies how to compute the route.
# @param string polyline_quality Optional. Specifies your preference for the quality of the polyline.
# @param string polyline_encoding Optional. Specifies the preferred encoding for the polyline.
# @param string departure_time Optional. The departure time.
# @param string arrival_time Optional. The arrival time.
# @param string compute_alternative_routes Optional. Specifies whether to calculate alternate routes in addition to the route.
# @param string route_modifiers_json Optional. The JSON object for RouteModifiers.
# @param string language_code Optional. The BCP-47 language code.
# @param string region_code Optional. The region code, specified as a ccTLD two-character value.
# @param string units Optional. Specifies the units of measure for the display fields.
# @param string optimize_waypoint_order Optional. If set to true, the service attempts to minimize the overall cost of the route by re-ordering the specified intermediate waypoints.
# @param string requested_reference_routes_json Optional. A JSON array of requested reference routes.
# @param string extra_computations_json Optional. A JSON array of extra computations.
# @param string traffic_model Optional. Specifies the assumptions to use when calculating time in traffic.
# @param string transit_preferences_json Optional. The JSON object for TransitPreferences.
# @return string The JSON object.
create_compute_routes_request_json() {
  local origin_json="$1"
  local destination_json="$2"
  local intermediates_json="${3:-""}"
  local travel_mode="${4:-""}"
  local routing_preference="${5:-""}"
  local polyline_quality="${6:-""}"
  local polyline_encoding="${7:-""}"
  local departure_time="${8:-""}"
  local arrival_time="${9:-""}"
  local compute_alternative_routes="${10:-""}"
  local route_modifiers_json="${11:-""}"
  local language_code="${12:-""}"
  local region_code="${13:-""}"
  local units="${14:-""}"
  local optimize_waypoint_order="${15:-""}"
  local requested_reference_routes_json="${16:-""}"
  local extra_computations_json="${17:-""}"
  local traffic_model="${18:-""}"
  local transit_preferences_json="${19:-""}"

  local json_output="{}"
  json_output=$(echo "${json_output}" | jq --argjson origin "${origin_json}" '.origin = $origin')
  json_output=$(echo "${json_output}" | jq --argjson destination "${destination_json}" '.destination = $destination')

  if [[ -n "${intermediates_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson intermediates "${intermediates_json}" '.intermediates = $intermediates')
  fi
  if [[ -n "${travel_mode}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg travelMode "${travel_mode}" '.travelMode = $travelMode')
  fi
  if [[ -n "${routing_preference}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg routingPreference "${routing_preference}" '.routingPreference = $routingPreference')
  fi
  if [[ -n "${polyline_quality}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg polylineQuality "${polyline_quality}" '.polylineQuality = $polylineQuality')
  fi
  if [[ -n "${polyline_encoding}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg polylineEncoding "${polyline_encoding}" '.polylineEncoding = $polylineEncoding')
  fi
  if [[ -n "${departure_time}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg departureTime "${departure_time}" '.departureTime = $departureTime')
  fi
  if [[ -n "${arrival_time}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg arrivalTime "${arrival_time}" '.arrivalTime = $arrivalTime')
  fi
  if [[ -n "${compute_alternative_routes}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson computeAlternativeRoutes "${compute_alternative_routes}" '.computeAlternativeRoutes = $computeAlternativeRoutes')
  fi
  if [[ -n "${route_modifiers_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson routeModifiers "${route_modifiers_json}" '.routeModifiers = $routeModifiers')
  fi
  if [[ -n "${language_code}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg languageCode "${language_code}" '.languageCode = $languageCode')
  fi
  if [[ -n "${region_code}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg regionCode "${region_code}" '.regionCode = $regionCode')
  fi
  if [[ -n "${units}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg units "${units}" '.units = $units')
  fi
  if [[ -n "${optimize_waypoint_order}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson optimizeWaypointOrder "${optimize_waypoint_order}" '.optimizeWaypointOrder = $optimizeWaypointOrder')
  fi
  if [[ -n "${requested_reference_routes_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson requestedReferenceRoutes "${requested_reference_routes_json}" '.requestedReferenceRoutes = $requestedReferenceRoutes')
  fi
  if [[ -n "${extra_computations_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson extraComputations "${extra_computations_json}" '.extraComputations = $extraComputations')
  fi
  if [[ -n "${traffic_model}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg trafficModel "${traffic_model}" '.trafficModel = $trafficModel')
  fi
  if [[ -n "${transit_preferences_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson transitPreferences "${transit_preferences_json}" '.transitPreferences = $transitPreferences')
  fi

  echo "${json_output}"
}

# Create a JSON object for a RouteMatrixOrigin
#
# @param string waypoint_json Required. The JSON object for Waypoint.
# @param string route_modifiers_json Optional. The JSON object for RouteModifiers.
# @return string The JSON object.
create_route_matrix_origin_json() {
  local waypoint_json="$1"
  local route_modifiers_json="${2:-""}"

  local json_output="{}"
  json_output=$(echo "${json_output}" | jq --argjson waypoint "${waypoint_json}" '.waypoint = $waypoint')

  if [[ -n "${route_modifiers_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson routeModifiers "${route_modifiers_json}" '.routeModifiers = $routeModifiers')
  fi

  echo "${json_output}"
}

# Create a JSON object for a RouteMatrixDestination
#
# @param string waypoint_json Required. The JSON object for Waypoint.
# @return string The JSON object.
create_route_matrix_destination_json() {
  local waypoint_json="$1"
  jq -n \
    --argjson waypoint "${waypoint_json}" \
    '{
      "waypoint": $waypoint
    }'
}

# Create a JSON object for a ComputeRouteMatrixRequest
#
# @param string origins_json Required. A JSON array of RouteMatrixOrigin objects.
# @param string destinations_json Required. A JSON array of RouteMatrixDestination objects.
# @param string travel_mode Optional. The mode of transportation.
# @param string routing_preference Optional. Specifies how to compute the route.
# @param string departure_time Optional. The departure time.
# @param string arrival_time Optional. The arrival time.
# @param string language_code Optional. The BCP-47 language code.
# @param string region_code Optional. The region code, specified as a ccTLD two-character value.
# @param string extra_computations_json Optional. A JSON array of extra computations.
# @param string traffic_model Optional. Specifies the assumptions to use when calculating time in traffic.
# @param string transit_preferences_json Optional. The JSON object for TransitPreferences.
# @return string The JSON object.
create_compute_route_matrix_request_json() {
  local origins_json="$1"
  local destinations_json="$2"
  local travel_mode="${3:-""}"
  local routing_preference="${4:-""}"
  local departure_time="${5:-""}"
  local arrival_time="${6:-""}"
  local language_code="${7:-""}"
  local region_code="${8:-""}"
  local extra_computations_json="${9:-""}"
  local traffic_model="${10:-""}"
  local transit_preferences_json="${11:-""}"

  local json_output="{}"
  json_output=$(echo "${json_output}" | jq --argjson origins "${origins_json}" '.origins = $origins')
  json_output=$(echo "${json_output}" | jq --argjson destinations "${destinations_json}" '.destinations = $destinations')

  if [[ -n "${travel_mode}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg travelMode "${travel_mode}" '.travelMode = $travelMode')
  fi
  if [[ -n "${routing_preference}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg routingPreference "${routing_preference}" '.routingPreference = $routingPreference')
  fi
  if [[ -n "${departure_time}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg departureTime "${departure_time}" '.departureTime = $departureTime')
  fi
  if [[ -n "${arrival_time}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg arrivalTime "${arrival_time}" '.arrivalTime = $arrivalTime')
  fi
  if [[ -n "${language_code}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg languageCode "${language_code}" '.languageCode = $languageCode')
  fi
  if [[ -n "${region_code}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg regionCode "${region_code}" '.regionCode = $regionCode')
  fi
  if [[ -n "${extra_computations_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson extraComputations "${extra_computations_json}" '.extraComputations = $extraComputations')
  fi
  if [[ -n "${traffic_model}" ]]; then
    json_output=$(echo "${json_output}" | jq --arg trafficModel "${traffic_model}" '.trafficModel = $trafficModel')
  fi
  if [[ -n "${transit_preferences_json}" ]]; then
    json_output=$(echo "${json_output}" | jq --argjson transitPreferences "${transit_preferences_json}" '.transitPreferences = $transitPreferences')
  fi

  echo "${json_output}"
}
