#!/bin/bash
#
# This script provides a client for the Routes API v2.
# It is not meant to be used directly, but rather to be sourced by other scripts.
#
# DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY A SCRIPT.
#
# Discovery Doc Revision: 20260706
#
# For more information, see the official documentation:
# https://developers.google.com/maps/documentation/routes/

# Source the internal helper script
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/api-common.sh"
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/routes_v2_helpers.sh"

# --- Routes API v2 ---

# Base URL for the Routes API
ROUTES_V2_BASE_URL="https://routes.googleapis.com/"

# --- Methods ---

# Returns the primary route along with optional alternate routes.
#
# @param string request_body The request body as a JSON string.
# @param string field_mask The fields to return in the response.
# @param string project_id Optional. The project ID for billing.
# @see https://developers.google.com/maps/documentation/routes/reference/rest/v2/routes/computeRoutes
routes_computeRoutes() {
  local request_body="$1"
  local field_mask="${2:-*}"
  local project_id="${3:-}"
  local additional_headers
  additional_headers="X-Goog-FieldMask: ${field_mask}"
  local url="${ROUTES_V2_BASE_URL}directions/v2:computeRoutes"
  _call_api "POST" "${url}" "${request_body}" "${project_id}" "${additional_headers}"
}

# Takes a list of origins and destinations and returns a stream containing route information.
#
# @param string request_body The request body as a JSON string.
# @param string field_mask The fields to return in the response.
# @param string project_id Optional. The project ID for billing.
# @see https://developers.google.com/maps/documentation/routes/reference/rest/v2/routes/computeRouteMatrix
routes_computeRouteMatrix() {
  local request_body="$1"
  local field_mask="${2:-*}"
  local project_id="${3:-}"
  local additional_headers
  additional_headers="X-Goog-FieldMask: ${field_mask}"
  local url="${ROUTES_V2_BASE_URL}distanceMatrix/v2:computeRouteMatrix"
  _call_api "POST" "${url}" "${request_body}" "${project_id}" "${additional_headers}"
}

routes_v2_computeRoutes() {
  routes_computeRoutes "$@"
}

routes_v2_computeRouteMatrix() {
  routes_computeRouteMatrix "$@"
}
