#!/bin/bash

set -euo pipefail

# This script is for internal use by the generated API clients.
# It is not meant to be used directly.
#
# DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY A SCRIPT.

# Cache the access token to avoid calling gcloud repeatedly.
_GAC_ACCESS_TOKEN=""

# _get_access_token ensures we only call gcloud once per script execution.
_get_access_token() {
  local project_id="${1:-}"
  local gcloud_args=()

  if [[ -n "${project_id}" ]]; then
    gcloud_args+=(--project="${project_id}")
  fi

  if [[ -z "${_GAC_ACCESS_TOKEN}" ]]; then
    _GAC_ACCESS_TOKEN=$(gcloud auth application-default print-access-token ${gcloud_args[@]+"${gcloud_args[@]}"})
  fi
  echo "${_GAC_ACCESS_TOKEN}"
}

# _build_query_params safely constructs a URL query string.
#
# @param ... Key-value pairs (e.g., "pageSize=10" "pageToken=abc").
#            Only pairs with a non-empty value are included.
_build_query_params() {
    local params=()
    for arg in "$@"; do
        local key="${arg%%=*}"
        local value="${arg#*=}"
        if [[ -n "$value" ]]; then
            # A more robust implementation would URL-encode the value.
            # For this use case, we assume values are safe.
            params+=("${key}=${value}")
        fi
    done

    if ((${#params[@]} > 0)); then
        (
            # Join the array with '&'
            IFS='&'
            echo "?${params[*]}"
        )
    else
        echo ""
    fi
}


# _call_api is a helper function to make API calls with a specific authentication policy.
#
# @param string method The HTTP method (e.g., GET, POST, DELETE).
# @param string url The full URL for the API endpoint.
# @param string body Optional. The request body as a JSON string.
# @param string project_id Optional. The project ID for auth and billing.
# @param string additional_headers Optional. A newline-separated string of additional headers.
# @param string auth_policy Optional. ANON_FIRST (default), AUTH_REQUIRED, or OAUTH_ONLY.
_call_api() {
  local method="$1"
  local url="$2"
  local body="${3:-}"
  local project_id="${4:-}"
  local additional_headers="${5:-}"
  local auth_policy="${6:-ANON_FIRST}" # Default to ANON_FIRST for this pilot

  local response_file
  response_file=$(mktemp)
  local status_code
  local curl_args=("-sS" "-X" "${method}")

  # Helper to parse and add additional headers
  _add_headers() {
    if [[ -n "${additional_headers}" ]]; then
      IFS=$'\n' read -ra header_array <<< "${additional_headers}"
      for header in "${header_array[@]}"; do
        echo "-H" "${header}"
      done
    fi
  }

  _try_unauthenticated() {
    local anon_args=("${curl_args[@]}")
    if [[ -n "${body}" ]]; then
      anon_args+=("-H" "Content-Type: application/json" "-d" "${body}")
    fi
    if [[ -n "${additional_headers}" ]]; then
      while read -r h; do anon_args+=("$h"); done < <(_add_headers)
    fi
    status_code=$(curl "${anon_args[@]}" -o "${response_file}" -w "%{http_code}" "${url}")
    [[ "${status_code}" -ge 200 && "${status_code}" -lt 300 ]]
  }

  _try_authenticated() {
    local auth_args=("${curl_args[@]}")
    local auth_url="${url}"

    # Try API Key first if allowed and available
    if [[ "${auth_policy}" != "OAUTH_ONLY" && -n "${GOOGLE_API_KEY:-}" ]]; then
      if [[ "${auth_url}" == *"?"* ]]; then
        auth_url+="&key=${GOOGLE_API_KEY}"
      else
        auth_url+="?key=${GOOGLE_API_KEY}"
      fi
    else
      # Use OAuth
      local effective_project="${project_id}"
      if [[ -z "${effective_project}" ]]; then
        effective_project=$(gcloud config get-value project 2>/dev/null || echo "")
      fi
      local access_token
      access_token=$(_get_access_token "${effective_project}")
      if [[ -z "${access_token}" ]]; then
        echo "Error: Failed to obtain OAuth token and no API key set." >&2
        return 1
      fi
      auth_args+=("-H" "Authorization: Bearer ${access_token}")
      if [[ -n "${effective_project}" ]]; then
        auth_args+=("-H" "X-Goog-User-Project: ${effective_project}")
      fi
    fi

    if [[ -n "${body}" ]]; then
      auth_args+=("-H" "Content-Type: application/json" "-d" "${body}")
    fi
    if [[ -n "${additional_headers}" ]]; then
      while read -r h; do auth_args+=("$h"); done < <(_add_headers)
    fi

    status_code=$(curl "${auth_args[@]}" -o "${response_file}" -w "%{http_code}" "${auth_url}")
    [[ "${status_code}" -ge 200 && "${status_code}" -lt 300 ]]
  }

  # --- Policy Execution ---
  case "${auth_policy}" in
    ANON_FIRST)
      if _try_unauthenticated; then
        cat "${response_file}"
        rm -f "${response_file}"
        return 0
      fi
      if _try_authenticated; then
        cat "${response_file}"
        rm -f "${response_file}"
        return 0
      fi
      ;;
    AUTH_REQUIRED|OAUTH_ONLY)
      if _try_authenticated; then
        cat "${response_file}"
        rm -f "${response_file}"
        return 0
      fi
      ;;
    *)
      echo "Error: Unknown authentication policy: ${auth_policy}" >&2
      rm -f "${response_file}"
      return 1
      ;;
  esac

  # If we reach here, all attempted methods failed
  echo "API call failed with status code ${status_code}:" >&2
  cat "${response_file}" >&2
  rm -f "${response_file}"
  return 1
}