#!/bin/bash
set -euo pipefail
#
# This script provides helper functions for creating JSON request bodies for the Analytics Hub API v1.
# It is meant to be sourced by other scripts.
#
# DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY A SCRIPT.
#
# For more information, see the official documentation:
# https://cloud.google.com/bigquery/docs/analytics-hub-introduction

# --- Request Body Helper Functions ---

# Creates a JSON object for a DataExchange.
# @param string display_name
# @param string description
# @param string primary_contact
# @param string documentation
# @param string icon
create_data_exchange_json() {
    jq -n --arg dn "$1" --arg desc "$2" --arg pc "$3" --arg doc "$4" --arg icon "$5" \
        '{displayName: $dn, description: $desc, primaryContact: $pc, documentation: $doc, icon: $icon}'
}

# Creates a JSON object for a BigQueryDatasetSource.
# @param string dataset
create_big_query_dataset_source_json() {
    jq -n --arg ds "$1" '{dataset: $ds}'
}

# Creates a JSON object for a Listing.
# @param string display_name
# @param string description
# @param string primary_contact
# @param string documentation
# @param string bigquery_dataset_source_json
# @param string data_provider_json
create_listing_json() {
    local display_name="$1"
    local description="$2"
    local primary_contact="$3"
    local documentation="$4"
    local bigquery_dataset_source_json="$5"
    local data_provider_json="$6"

    local json_output="{}"
    json_output=$(echo "${json_output}" | jq --arg dn "$display_name" '.displayName = $dn')
    json_output=$(echo "${json_output}" | jq --arg desc "$description" '.description = $desc')
    json_output=$(echo "${json_output}" | jq --arg pc "$primary_contact" '.primaryContact = $pc')
    json_output=$(echo "${json_output}" | jq --arg doc "$documentation" '.documentation = $doc')

    if [[ -n "${bigquery_dataset_source_json}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson bqds "${bigquery_dataset_source_json}" '.bigqueryDataset = $bqds')
    fi

    if [[ -n "${data_provider_json}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson dp "${data_provider_json}" '.dataProvider = $dp')
    fi

    local pubsub_topic_source_json="${7:-}"
    if [[ -n "${pubsub_topic_source_json}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson psts "${pubsub_topic_source_json}" '.pubsubTopic = $psts')
    fi

    echo "${json_output}"
}

# Creates a JSON object for a PubSubTopicSource.
# @param string topic
create_pubsub_topic_source_json() {
    jq -n --arg tp "$1" '{topic: $tp}'
}

# Creates a JSON object for a DataProvider.
# @param string name
# @param string primary_contact
create_data_provider_json() {
    jq -n --arg name "$1" --arg pc "$2" '{name: $name, primaryContact: $pc}'
}

# Creates a JSON object for a DestinationDataset.
# @param string dataset_id Required. The ID of the dataset to create. e.g. "my_linked_dataset"
# @param string project_id Required. The project ID containing the destination dataset. e.g. "my-project"
# @param string location Optional. Geographic location where the dataset should reside (default: "us").
# @param string friendly_name Optional. A descriptive name for the dataset.
# @param string description Optional. A user-friendly description of the dataset.
create_destination_dataset_json() {
    local dataset_id="$1"
    local project_id="$2"
    local location="${3:-us}"
    local friendly_name="${4:-}"
    local description="${5:-}"

    local json_output
    json_output=$(jq -n \
        --arg did "$dataset_id" \
        --arg pid "$project_id" \
        --arg loc "$location" \
        '{datasetReference: {datasetId: $did, projectId: $pid}, location: $loc}')

    if [[ -n "${friendly_name}" ]]; then
        json_output=$(echo "${json_output}" | jq --arg fn "$friendly_name" '.friendlyName = $fn')
    fi
    if [[ -n "${description}" ]]; then
        json_output=$(echo "${json_output}" | jq --arg desc "$description" '.description = $desc')
    fi
    echo "${json_output}"
}

# Creates a JSON object for a SubscribeListingRequest.
# @param string destination_dataset_or_json (Accepts DestinationDataset JSON or dataset resource path "projects/P/datasets/D")
# @param string location Optional. Location of the destination dataset (default: "us").
create_subscribe_listing_request_json() {
    local arg="$1"
    local location="${2:-us}"
    if [[ "${arg}" =~ ^[[:space:]]*\{ ]]; then
        jq -n --argjson dd "${arg}" '{destinationDataset: $dd}'
    elif [[ "${arg}" =~ ^projects/([^/]+)/datasets/([^/]+)$ ]]; then
        local pid="${BASH_REMATCH[1]}"
        local did="${BASH_REMATCH[2]}"
        jq -n --arg pid "$pid" --arg did "$did" --arg loc "$location" \
            '{destinationDataset: {datasetReference: {projectId: $pid, datasetId: $did}, location: $loc}}'
    else
        jq -n --arg dd "${arg}" '{destinationDataset: $dd}'
    fi
}

# Creates a JSON object for a BigtableConfig.
# @param string app_profile_id Optional.
# @param string service_account_email Optional.
# @param string table Optional.
# @param boolean write_metadata Optional. (true/false)
create_bigtable_config_json() {
    local app_profile_id="${1:-}"
    local service_account_email="${2:-}"
    local table="${3:-}"
    local write_metadata="${4:-}"

    local json_output="{}"
    if [[ -n "${app_profile_id}" ]]; then
        json_output=$(echo "${json_output}" | jq --arg ap "${app_profile_id}" '.appProfileId = $ap')
    fi
    if [[ -n "${service_account_email}" ]]; then
        json_output=$(echo "${json_output}" | jq --arg sae "${service_account_email}" '.serviceAccountEmail = $sae')
    fi
    if [[ -n "${table}" ]]; then
        json_output=$(echo "${json_output}" | jq --arg t "${table}" '.table = $t')
    fi
    if [[ -n "${write_metadata}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson wm "${write_metadata}" '.writeMetadata = $wm')
    fi
    echo "${json_output}"
}

# Creates a JSON object for a Compression.
# @param string compression_algorithm Required. (e.g. COMPRESSION_ALGORITHM_UNSPECIFIED, ZLIB)
# @param string compression_mode Required. (e.g. COMPRESSION_MODE_UNSPECIFIED, COMPRESS, DECOMPRESS)
create_compression_json() {
    jq -n --arg ca "$1" --arg cm "$2" '{compressionAlgorithm: $ca, compressionMode: $cm}'
}

# Creates a JSON object for a MessageTransform with Compression.
# @param string compression_json Required.
# @param boolean disabled Optional. (true/false)
create_message_transform_json() {
    local compression_json="$1"
    local disabled="${2:-}"

    local json_output="{}"
    if [[ -n "${compression_json}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson comp "${compression_json}" '.compression = $comp')
    fi
    if [[ -n "${disabled}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson dis "${disabled}" '.disabled = $dis')
    fi
    echo "${json_output}"
}

# Creates a JSON object for a GooglePubsubV1Subscription.
# @param string name Required. (e.g. projects/{project}/subscriptions/{sub})
# @param string bigtable_config_json Optional.
# @param string message_transforms_json_array Optional. (e.g. [{"compression": ...}])
create_pubsub_subscription_json() {
    local name="$1"
    local bigtable_config_json="${2:-}"
    local message_transforms_json_array="${3:-}"

    local json_output="{}"
    json_output=$(echo "${json_output}" | jq --arg n "$name" '.name = $n')

    if [[ -n "${bigtable_config_json}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson btc "${bigtable_config_json}" '.bigtableConfig = $btc')
    fi
    if [[ -n "${message_transforms_json_array}" ]]; then
        json_output=$(echo "${json_output}" | jq --argjson mt "${message_transforms_json_array}" '.messageTransforms = $mt')
    fi
    echo "${json_output}"
}

# Creates a JSON object for a DestinationPubSubSubscription.
# @param string pubsub_subscription_json Required. (GooglePubsubV1Subscription)
create_destination_pubsub_subscription_json() {
    jq -n --argjson ps "$1" '{pubsubSubscription: $ps}'
}

# Creates a JSON object for a SubscribeListingRequest with Pub/Sub.
# @param string destination_pubsub_subscription_json Required. (DestinationPubSubSubscription)
create_subscribe_listing_request_pubsub_json() {
    jq -n --argjson dps "$1" '{destinationPubsubSubscription: $dps}'
}


