#!/bin/bash

set -euo pipefail

# This script is for internal use by the generated API clients.
# It is not meant to be used directly.
#
# DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY A SCRIPT.

# Cache the access token to avoid calling gcloud repeatedly.
_GAC_ACCESS_TOKEN=""

# _get_access_token ensures we only call gcloud once per script execution.
_get_access_token() {
  local project_id="${1:-}"
  local gcloud_args=()

  if [[ -n "${project_id}" ]]; then
    gcloud_args+=(--project="${project_id}")
  fi

  if [[ -z "${_GAC_ACCESS_TOKEN}" ]]; then
    _GAC_ACCESS_TOKEN=$(gcloud auth application-default print-access-token ${gcloud_args[@]+"${gcloud_args[@]}"})
  fi
  echo "${_GAC_ACCESS_TOKEN}"
}

# _build_query_params safely constructs a URL query string.
#
# @param ... Key-value pairs (e.g., "pageSize=10" "pageToken=abc").
#            Only pairs with a non-empty value are included.
_build_query_params() {
    local params=()
    for arg in "$@"; do
        local key="${arg%%=*}"
        local value="${arg#*=}"
        if [[ -n "$value" ]]; then
            # A more robust implementation would URL-encode the value.
            # For this use case, we assume values are safe.
            params+=("${key}=${value}")
        fi
    done

    if ((${#params[@]} > 0)); then
        (
            # Join the array with '&'
            IFS='&'
            echo "?${params[*]}"
        )
    else
        echo ""
    fi
}


# _call_api is a helper function to make authenticated API calls.
#
# @param string method The HTTP method (e.g., GET, POST, DELETE).
# @param string url The full URL for the API endpoint.
# @param string body Optional. The request body as a JSON string.
# @param string additional_headers Optional. A newline-separated string of additional headers.
_call_api() {
  local method="$1"
  local url="$2"
  local body="${3:-}"
  local project_id="${4:-}" # Project ID passed from the service client
  local additional_headers="${5:-}" # New parameter for additional headers
  local access_token
  access_token=$(_get_access_token "${project_id}") # Pass project_id to get_access_token

  if [[ -z "${access_token}" ]]; then
    echo "Error: Not authenticated. Please run 'gcloud auth application-default login'." >&2
    return 1
  fi

  # Add -S to show errors
  local curl_args=("-sS" "-X" "${method}")
  curl_args+=("-H" "Authorization: Bearer ${access_token}")

  # Add the quota project header if a project_id was provided.
  if [[ -n "${project_id}" ]]; then
    curl_args+=("-H" "X-Goog-User-Project: ${project_id}")
  fi

  # Parse and add additional headers
  if [[ -n "${additional_headers}" ]]; then
    IFS=$'\n' read -ra header_array <<< "${additional_headers}"
    for header in "${header_array[@]}"; do
      curl_args+=("-H" "${header}")
    done
  fi

  if [[ -n "${body}" ]]; then
    curl_args+=("-H" "Content-Type: application/json")
    curl_args+=("-d" "${body}")
  fi

  curl "${curl_args[@]}" "${url}"
}